# Generated by Django 5.1.2 on 2024-11-26 03:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_shipping_charges_alter_order_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('f8f2e5a4-9a97-4c31-ae05-db3aedd6c779'), primary_key=True, serialize=False),
        ),
    ]
